site_name: Calculadora de conjuntos numéricos

theme:
  name: material

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - with-pdf:
      author: Evandro Ribeiro da Silva Neto
      copyright: ' '
      cover_title: Calculadora de conjuntos numericos
      cover_subtitle: Documentação
      output_path: document.pdf
      toc_title: Sumário
      heading_shift: false
